### ISSUE TITLE
Toolkit

### ISSUE THREAD

**Issue by treba123** [loklak/asksusi_android#1]
As the app will probably not need any low level functions, I think it would make sense to write the app with a focus on portability, so we can easily port it to ios and windows.

What do you think @shivenmian ? Should we just write the app in HTML5 or something?
Or is it better to write it in java?

**Comment by shivenmian** [comment]
Yes this is what I have been thinking.

Let's write the app in React.js if we can. It's a UI framework for coding beautiful apps in JavaScript (React). Check out [React Native](https://facebook.github.io/react-native).

**Comment by treba123** [comment]
That sounds cool, let's do that.

**Comment by mariobehling** [comment]
I would like to be sure all requirements are taken into account. Susi should become:
* a chat search application, where a user gets answers from an AI bot
* it should be possible to invite other friends and chat together with Susi in a group chat
* the app should be able to embed all kinds of media, e.g. a map
* if a user logsin the history should be stored on the server and it should be possible to improve future answers based on the chat history
* Susi should be able to connect other services, e.g. twitter, facebook etc.

Question: Can it be integrated with loklak_depot?

**Comment by shivenmian** [comment]
@mariobehling @treba123 As of now, I'm just thinking on making the interface and get the app running first of all (like asksusi.com) and make the app answer normal queries. 

Once we are done with the basic app, we can then integrate accounts, chat history, Social Media integration and learning from past conversations.

**Comment by shivenmian** [comment]
Elaborated on this in https://github.com/loklak/asksusi_android/issues/5
